[versions]
sshj = "0.40.0"
dropbox-sdk = "7.0.0"
google-api-client = "2.8.1"
google-api-drive = "v3-rev20251210-2.0.0"
google-auth-library = "1.41.0"
gson = "2.13.2"
jetbrains-annotations = "26.0.2-1"
junit-bom = "6.0.1"
logback-classic = "1.5.22"
metadata-extractor = "2.19.0"
mockito = "5.21.0"
slf4j-api = "2.0.17"
task-tree = "4.0.1"
aws-sdk-s3 = "2.40.8"

[libraries]
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
dropbox-sdk = { module = "com.dropbox.core:dropbox-core-sdk", version.ref = "dropbox-sdk" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "google-api-client" }
google-api-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "google-api-drive" }
google-auth-library = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "google-auth-library" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
metadata-extractor = { module = "com.drewnoakes:metadata-extractor", version.ref = "metadata-extractor"}
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-sdk-s3" }

[plugins]
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }

[bundles]
mockito-all = ["mockito-core", "mockito-junit"]
google-all = ["google-api-client", "google-api-drive", "google-auth-library", "gson"]
aws-all = ["aws-sdk-s3"]
